### ISSUE TITLE
Problem working with avalonia on multi-container project

### ISSUE THREAD

**Issue by andreriesco** [toradex/vscode-torizon-templates#269]
When opening a multi-container project that contains an Avalonia template, the following error happens:
```
Using dotnet configured on PATH
Dotnet path: /usr/share/dotnet/dotnet
Activating C# standalone...
waiting for named pipe information from server...
[stdout] {"pipeName":"/tmp/035c5ecc.sock"}
received named pipe information from server
attempting to connect client to server...
client has connected to server
[Info  - 9:23:36 AM] [Program] Language server initialized
[Warn  - 9:23:38 AM] [LanguageServerProjectSystem] Project /home/andreriesco/Documents/IDE2.0/test-applications/testAvalonia77/avalonia/avalonia.csproj has unresolved dependencies
    Avalonia-11.0.11
[Error - 9:23:38 AM] [LanguageServerProjectSystem] Error while loading /home/andreriesco/Documents/IDE2.0/test-applications/testAvalonia77/avalonia/avalonia.csproj: Cycle detected. 
  avalonia -> Avalonia (>= 11.0.11).
[Info  - 9:23:38 AM] [Microsoft.CodeAnalysis.LanguageServer.DotnetCliHelper] Using dotnet executable configured on the PATH
[Info  - 9:23:40 AM] [LanguageServerProjectSystem] Completed (re)load of all projects in 00:00:03.2524994
[Error - 9:23:41 AM] [LanguageServerHost] System.ArgumentException: ".." can be only added at the beginning of the pattern.
   at Microsoft.Extensions.FileSystemGlobbing.Internal.Patterns.PatternBuilder.Build(String pattern)
   at Microsoft.Extensions.FileSystemGlobbing.Matcher.AddInclude(String pattern)
   at Microsoft.Extensions.FileSystemGlobbing.MatcherExtensions.AddIncludePatterns(Matcher matcher, IEnumerable`1[] includePatternsGroups)
   at Microsoft.CodeAnalysis.LanguageServer.HostWorkspace.LoadedProject.<>c.<UpdateWithNewProjectInfoAsync>b__18_19(FileGlobs glob) in /_/src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LoadedProject.cs:line 230
   at System.Linq.Enumerable.SelectArrayIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.CodeAnalysis.LanguageServer.HostWorkspace.LoadedProject.FileChangedContext_FileChanged(Object sender, String filePath) in /_/src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LoadedProject.cs:line 76
   at Microsoft.CodeAnalysis.LanguageServer.HostWorkspace.FileWatching.LspFileChangeWatcher.FileChangeContext.WatchedFilesHandler_OnNotificationRaised(Object sender, DidChangeWatchedFilesParams e) in /_/src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/LspFileChangeWatcher.cs:line 114
   at Microsoft.CodeAnalysis.LanguageServer.HostWorkspace.FileWatching.LspDidChangeWatchedFilesHandler.Microsoft.CommonLanguageServerProtocol.Framework.INotificationHandler<Roslyn.LanguageServer.Protocol.DidChangeWatchedFilesParams,Microsoft.CodeAnalysis.LanguageServer.Handler.RequestContext>.HandleNotificationAsync(DidChangeWatchedFilesParams request, RequestContext requestContext, CancellationToken cancellationToken) in /_/src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/LspDidChangeWatchedFilesHandler.cs:line 28
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`1.StartRequestAsync[TRequest,TResponse](TRequest request, TRequestContext context, IMethodHandler handler, String language, CancellationToken cancellationToken) in /_/src/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 199
```

And then when trying to run the project, the following error happens:
```
 *  Executing task in folder avalonia: dotnet publish /home/andreriesco/Documents/IDE2.0/test-applications/testAvalonia77/avalonia/avalonia.csproj /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary -c Debug -r linux-arm64 --no-self-contained 

  Determining projects to restore...
/home/andreriesco/Documents/IDE2.0/test-applications/testAvalonia77/avalonia/avalonia.csproj : error NU1108: Cycle detected. 
/home/andreriesco/Documents/IDE2.0/test-applications/testAvalonia77/avalonia/avalonia.csproj : error NU1108:   avalonia -> Avalonia (>= 11.0.11).
  Failed to restore /home/andreriesco/Documents/IDE2.0/test-applications/testAvalonia77/avalonia/avalonia.csproj (in 337 ms).

 *  The terminal process "dotnet 'publish', '/home/andreriesco/Documents/IDE2.0/test-applications/testAvalonia77/avalonia/avalonia.csproj', '/property:GenerateFullPaths=true', '/consoleloggerparameters:NoSummary', '-c', 'Debug', '-r', 'linux-arm64', '--no-self-contained'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 
```

**Comment by microhobby** [comment]
This is a known limitation, you should not name your app the same name of the framework.
